help icerikleri eklendi

diff --git a/evam-plugins/check_evam_engine_errorCount b/evam-plugins/check_evam_engine_errorCount
--- a/evam-plugins/check_evam_engine_errorCount
+++ b/evam-plugins/check_evam_engine_errorCount
@@ -3,30 +3,52 @@
 RUN_DIR_PATH=$PWD
 source /etc/evam.conf
 
-USAGE="`basename $0` [-w|--warning]<qsize> [-c|--critical]<qsize>"
+USAGE="`basename $0` [-w|--warning]<qsize> [-c|--critical]<qsize> [-h|--help]<help>"
 THRESHOLD_USAGE="WARNING threshold must be less than CRITICAL: `basename $0` $*"
-
 critical=""
 warning=""
 STATE_OK=0
 STATE_WARNING=1
 STATE_CRITICAL=2
 STATE_UNKNOWN=3
-# print usage
-if [[ $# -lt 4 ]]
-then
-        echo ""
-        echo "Wrong Syntax: `basename $0` $*"
-        echo ""
-        echo "Usage: $USAGE"
-        echo ""
-        exit 0
-fi
+
+PROGNAME=`basename $0`
+
+print_help(){
+        echo "$PROGNAME is a Nagios Plugin to check engine error log sizes"
+        echo "See below for available options."
+        echo "Options:"
+        echo "  -w/--warning)"
+        echo "          Defines warning threshold of error log count"
+        echo "  -c/--critical)"
+        echo "          Defines critical threshold of error log count"
+     
+}
+
+
+
+        if [[ $# -lt 3 && $1 -ne "-h" ]]
+        then
+                echo ""
+                echo "Wrong Syntax: `basename $0` $*"
+                echo ""
+                echo "Usage: $USAGE"
+		echo ""
+                exit 0
+        fi
+
+
+
+
 # read input
 while [[ $# -gt 0 ]]
   do
         case "$1" in
-               -w|--warning)
+               -h|--help)
+	       print_help
+	       exit 3
+	;;
+	       -w|--warning)
                shift
                warning=$1
         ;;
@@ -37,6 +59,11 @@ while [[ $# -gt 0 ]]
         esac
         shift
   done
+
+
+
+
+
 # verify input
 if [[ $warning -eq $critical || $critical -lt $warning ]]
 then
